### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by jmorenou** [miraxes/angular-custom-tour#4]
I have this error:
ERROR in Error: HintModule is not an NgModule

**Comment by miraxes** [comment]
@jmorenou  I need more info to reproduce that error.

**Comment by miraxes** [comment]
@jmorenou  Oops, there are was error with latest Angular CLI, currently it is already fixed, just use latest version of package it is `0.0.17` ATM.

Thanks for your attention.

**Comment by jmorenou** [comment]
Good morning. 
The error is this:
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'E:\Ilumno\Fuentes\Desarrollo\Presentacion\UI.WebCore\src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts

ERROR in Error: Unexpected value 'HintModule in E:/Ilumno/Fuentes/Desarrollo/Presentacion/UI.WebCore/node_modules/angular-custom-tour/src/index.d.ts' imported by the module 'IlumnoScoreCardModule in E:/Ilumno/Fuentes/Desarrollo/Presentacion/UI.WebCore/src/app/layout/ilumno-scorecard/ilumno-scorecard.module.ts'. Please add a @NgModule annotation.
    at Error (native)
    at syntaxError (E:\Ilumno\Fuentes\Desarrollo\Presentacion\UI.WebCore\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at E:\Ilumno\Fuentes\Desarrollo\Presentacion\UI.WebCore\node_modules\@angular\compiler\bundles\compiler.umd.js:15433:44
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (E:\Ilumno\Fuentes\Desarrollo\Presentacion\UI.WebCore\node_modules\@angular\compiler\bundles\compiler.umd.js:15416:49)
    at addNgModule (E:\Ilumno\Fuentes\Desarrollo\Presentacion\UI.WebCore\node_modules\@angular\compiler\bundles\compiler.umd.js:24268:58)
    at E:\Ilumno\Fuentes\Desarrollo\Presentacion\UI.WebCore\node_modules\@angular\compiler\bundles\compiler.umd.js:24279:14
    at Array.forEach (native)
    at _createNgModules (E:\Ilumno\Fuentes\Desarrollo\Presentacion\UI.WebCore\node_modules\@angular\compiler\bundles\compiler.umd.js:24278:26)
    at analyzeNgModules (E:\Ilumno\Fuentes\Desarrollo\Presentacion\UI.WebCore\node_modules\@angular\compiler\bundles\compiler.umd.js:24153:14)
    at analyzeAndValidateNgModules (E:\Ilumno\Fuentes\Desarrollo\Presentacion\UI.WebCore\node_modules\@angular\compiler\bundles\compiler.umd.js:24163:35)
    at AotCompiler.analyzeModulesAsync (E:\Ilumno\Fuentes\Desarrollo\Presentacion\UI.WebCore\node_modules\@angular\compiler\bundles\compiler.umd.js:23797:46)
    at CodeGenerator.codegen (E:\Ilumno\Fuentes\Desarrollo\Presentacion\UI.WebCore\node_modules\@angular\compiler-cli\src\codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (E:\Ilumno\Fuentes\Desarrollo\Presentacion\UI.WebCore\node_modules\@angular\compiler-cli\src\ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (E:\Ilumno\Fuentes\Desarrollo\Presentacion\UI.WebCore\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\plugin.js:430:58


PACKAGE.JSON Dependencies

"dependencies": {
        "@angular/animations": "^4.4.6",
        "@angular/common": "^4.4.6",
        "@angular/compiler": "^4.4.6",
        "@angular/core": "^4.4.6",
        "@angular/forms": "^4.4.6",
        "@angular/http": "^4.4.6",
        "@angular/platform-browser": "^4.4.6",
        "@angular/platform-browser-dynamic": "^4.4.6",
        "@angular/router": "^4.4.6",
        "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.30",
        "@ngx-translate/core": "^7.2.2",
        "@ngx-translate/http-loader": "^0.1.0",
        "angular-custom-tour": "0.0.16",
        "angular-oauth2-oidc": "^2.1.8",
        "angular2-bootstrap-switch": "^0.2.3",
        "angular2-hotkeys": "^2.0.3",
        "angular2-in-memory-web-api": "0.0.21",
        "core-js": "^2.5.3",
        "enhanced-resolve": "^3.3.0",
        "font-awesome": "^4.7.0",
        "ng2-cache": "^0.1.11",
        "ng2-charts": "^1.6.0",
        "ngx-cookie": "^1.0.1",
        "ngx-infinite-scroll": "^0.5.2",
        "ngx-loading": "^1.0.9",
        "rxjs": "^5.5.5",
        "zone.js": "^0.8.18"
    },
    "devDependencies": {
        "@angular/cli": "^1.6.1",
        "@angular/compiler-cli": "^4.4.6",
        "@angular/language-service": "^4.4.6",
        "@types/jasmine": "2.5.45",
        "@types/node": "^6.0.93",
        "codelyzer": "~3.0.1",
        "jasmine-core": "~2.6.2",
        "jasmine-spec-reporter": "~4.1.0",
        "karma": "~1.7.0",
        "karma-chrome-launcher": "~2.1.1",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "^1.2.1",
        "karma-jasmine": "^1.1.1",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.1.2",
        "ts-node": "~3.0.4",
        "tslint": "~5.3.2",
        "typescript": "~2.3.3"
    }

Thank you so much

**Comment by miraxes** [comment]
@jmorenou 
As I described above, already fixed that issue, just use latest version of package
in your `package.json`

`"angular-custom-tour": "0.0.16",` => `"angular-custom-tour": "0.0.17"`,
 and reinstall package
rm node_modules/angular-custom-tour && npm install

**Comment by jmorenou** [comment]
It works. Thank you so much, you save me.
